title: English Creative Center
email: your-email@domain.com
description:

facebook: https://www.facebook.com/ecchanoi/
email: englishcreativecentre@gmail.com
address: 17B, ngach 32/53 An Duong, Tay&nbsp;Ho, Hanoi, Vietnam
phone: 091 940 94 64

# Server Config options
url: 127.0.0.1:4000
livereload: true

collections:
  courses:
    title: Courses
    output: false

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/logo.svg

ceo:
  type: LocalBusiness

image: /assets/images/logo.svg

social:
  name: English Creative Center
  links:
    https://www.facebook.com/ecchanoi/

facebook:
  publisher: English Creative Center

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-livereload
