title: English Creative Center
email: your-email@domain.com
description: 

facebook: jekyllrb
email:  jekyll
address:
phone:


collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
