title: English Creative Center
email: your-email@domain.com
description:

facebook: https://www.facebook.com/ecchanoi/
email: englishcreativecentre@gmail.com
address: 17B, ngach 32/53 An Duong, Tay&nbsp;Ho, Hanoi, Vietnam
phone: 091 940 94 64

# Server Config options
livereload: true

collections:
  courses:
    title: Courses
    output: true
  posts:
    title: Posts
    output: true

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-sitemap
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-livereload
  - jekyll-seo-tag
